apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test-ratelimit
  namespace: traefik
spec:
  rateLimit:
    average: 100
    burst: 200
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{cookiecutter.project}}-ingress
  namespace: {{cookiecutter.project}}
  annotations:
    cert-manager.io/cluster-issuer: http-01-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure, web
    traefik.ingress.kubernetes.io/router.middlewares: traefik-test-ratelimit@kubernetescrd
  labels:
    name: {{cookiecutter.project}}-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: {{cookiecutter.domain}}
      http:
        paths:
          - pathType: Prefix
            path: "/{{cookiecutter.project.lower()}}"
            backend:
              service:
                name: {{cookiecutter.project}}-service
                port:
                  number: 8000
{% if cookiecutter.tls %}
  tls:
    - hosts:
        - {{cookiecutter.domain}}
      secretName: {{cookiecutter.domain}}
  {% endif %}