---
apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.project}}-service
  namespace: {{cookiecutter.project}}
spec:
  type: ClusterIP
  ports:
    - port: {{cookiecutter.port}}
      targetPort: http
  selector:
    app: {{cookiecutter.project}}